const folio = [
    {
      id: 1,
      title: 'Infusion Brewing Co.',
      category: 'Print Design',
      subtitle: 'Product Branding & Website Design',
      subcat: ['Product Logo Design', 'Product Packaging', 'Website Design', 'Illustration'],
      img: '/images/inf-hero.jpg',
      desc: `This is the intro text for Infusion Brewing Co. `,
      pageref: '/portfolio/inf',
      
    },
    {
      id: 2,
      title: 'Paramount Pools',
      category: 'Web Design',
      subtitle: 'eCommerce Website',
      subcat: ['Product Logo Design', 'Product Packaging', 'Website Design', 'Illustration'],
      img: './images/pmt-hero.jpg',
      desc: `This is the intro text for PAramount Pools NZ `,
      pageref: '/portfolio/pmt',
    },
    {
      id: 3,
      title: 'VirtuVisit',
      category: 'Branding',
      subtitle: 'eCommerce Website',
      subcat: ['Brand Name', 'Brand Identity', 'Product Design', 'Website Design'],
      img: './images/vvt-hero.jpg',
      desc: `Description for VirtuVisit project here `,
      pageref: '/portfolio/vvt',
    },
    {
      id: 4,
      title: 'Pub Culture Beercations',
      category: 'Branding',
      subtitle: 'Brand Package',
      subcat: ['Brand Identity', 'Stationery Collateral', 'Website Design'],
      img: './images/pcb-hero.jpg',
      desc: `Description for Pub Culture Beercation project here `,
      pageref: '/portfolio/pcb',
    },
    {
      id: 5,
      title: 'Martronics',
      category: 'Web Design',
      subtitle: 'Website Redesign',
      subcat: 'Website Design',
      img: './images/mar-hero.jpg',
      desc: `Description for Pub Culture Beercation project here `,
      pageref: '/portfolio/mar',    
    },
    {
      id: 6,
      title: 'Logo Designs',
      category: 'Branding',
      subtitle: 'Assorted Logo Designs',
      subcat: ['Design', 'Illustration', 'Branding'],
      img: './images/log-hero.jpg',
      desc: `Over the years we've developed identities for companies big and small. `,
      pageref: '/portfolio/log',    
    },
    {
      id: 7,
      title: 'Precise BioScience',
      category: 'Web Design',
      subtitle: 'Assorted Logo Designs',
      subcat: ['Design', 'Illustration', 'Branding'],
      img: './images/log-hero.jpg',
      desc: `Over the years we've developed identities for companies big and small. `,
      pageref: '/portfolio/log',    
    },
    {
      id: 8,
      title: 'Phillbrook',
      category: 'Web Design',
      subtitle: 'Assorted Logo Designs',
      subcat: ['Design', 'Illustration', 'Branding'],
      img: './images/log-hero.jpg',
      desc: `Over the years we've developed identities for companies big and small. `,
      pageref: '/portfolio/log',    
    },
    {
      id: 9,
      title: 'Metro Sports TV',
      category: 'Web Design',
      subtitle: 'Assorted Logo Designs',
      subcat: ['Design', 'Illustration', 'Branding'],
      img: './images/log-hero.jpg',
      desc: `Over the years we've developed identities for companies big and small. `,
      pageref: '/portfolio/log',    
    },
    {
      id: 10,
      title: 'Emerald Limousine',
      category: 'Branding',
      subtitle: 'Assorted Logo Designs',
      subcat: ['Design', 'Illustration', 'Branding'],
      img: './images/log-hero.jpg',
      desc: `Over the years we've developed identities for companies big and small. `,
      pageref: '/portfolio/log',    
    },
  ];
  export default folio;